name: CI

on:
  push

env:
  MIX_ENV: test

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [1.13]
        otp: [24.2]
    steps:
      - uses: actions/checkout@v2
      - name: Setup elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - name: Install Mix dependencies
        run: mix deps.get
      - name: Check Formatting
        run: mix format mix.exs "lib/**/*.{ex,exs}" --check-formatted
      - name: Compile dependencies
        run: mix deps.compile -f
      - name: Compile Mix app
        run: mix compile -f
      - name: Run tests
        run: mix test
